alter session set container = instituto;

grant connect,resource to usuario;

-- crear las tablas en ese esquema
create table usuario.profesor (
   cod_prof number(2) GENERATED BY DEFAULT AS IDENTITY
      PRIMARY KEY,
   nombre   varchar2(30) not null,
   apellido varchar2(30) not null
);

create table usuario.alumno (
   cod_alumn number(2) GENERATED BY DEFAULT AS IDENTITY
      PRIMARY KEY,
   nombre    varchar2(30) not null,
   apellido  varchar2(30),
   edad      number(2),
   cod_tutor number(2),
   constraint fk_alumno_profesor foreign key ( cod_tutor )
      references usuario.profesor ( cod_prof )
);

-- Insertar datos iniciales 
INSERT INTO usuario.profesor (nombre, apellido)
VALUES ('Eva', 'Pinilla');

INSERT INTO usuario.alumno (nombre, apellido, edad, cod_tutor)
VALUES ('Luismi', 'Lopez', 19, 1);

INSERT INTO usuario.profesor (nombre, apellido)
VALUES ('Julian', 'Parra');

INSERT INTO usuario.alumno (nombre, apellido, edad, cod_tutor)
VALUES ('Toni', 'Sancha', 20, 2);

INSERT INTO usuario.alumno (nombre, apellido, edad, cod_tutor)
VALUES ('David', 'Oliva', 19, 2);