package es.etg.dam.acceso.dao.oracle;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import es.etg.dam.acceso.dao.AlumnoDAO;
import es.etg.dam.acceso.model.Alumno;

public class AlumnoOracleXeDAOImp implements AlumnoDAO {

    private final Connection conn;

    public AlumnoOracleXeDAOImp() throws Exception {
        conn = ConexionOracle.obtenerConexion().getConn();
    }

    @Override
    public void crearTabla() throws SQLException {
        final String query = """
                CREATE TABLE alumno (
                    cod_alumn number(2) GENERATED BY DEFAULT AS IDENTITY
                    PRIMARY KEY,
                    nombre    varchar2(30) not null,
                    apellido  varchar2(30),
                    edad      number(2),
                    cod_tutor number(2),
                    constraint fk_alumno_profesor foreign key ( cod_tutor )
                    references usuario.profesor ( cod_prof )
                )
                """;
        try (PreparedStatement ps = conn.prepareStatement(query)) {
            ps.execute();
        }
    }

    @Override
    public int insertar(Alumno a) throws SQLException {
        final String query = """
                INSERT INTO alumno (nombre, apellido, edad, cod_tutor)
                VALUES (?,?,?,?)
                """;

        try (PreparedStatement ps = conn.prepareStatement(query)) {
            ps.setString(1, a.getNombre());
            ps.setString(2, a.getApellido());
            ps.setInt(3, a.getEdad());
            ps.setInt(4, a.getCodTutor());
            ps.executeUpdate();
            ResultSet rs = ps.getGeneratedKeys();
            if (rs.next()){
                a.setCodAlumno(rs.getLong(1));
            }
            
            return 1;
        }
    }

    @Override
    public int actualizar(Alumno a) throws SQLException {
        final String query = """
                UPDATE alumno
                SET nombre = ?, apellido = ?, edad = ?, cod_tutor = ?
                WHERE cod_alumn = ?
                """;

        try (PreparedStatement ps = conn.prepareStatement(query)) {
            ps.setString(1, a.getNombre());
            ps.setString(2, a.getApellido());
            ps.setInt(3, a.getEdad());
            ps.setInt(4, a.getCodTutor());
            ps.setLong(5, a.getCodAlumno());
            return ps.executeUpdate();
        }
    }

    @Override
    public List<Alumno> listarAll() throws SQLException {
        final String query = "SELECT cod_alumn, nombre, apellido, edad, cod_tutor FROM alumno";

        List<Alumno> alumnos = new ArrayList<>();
        try (PreparedStatement ps = conn.prepareStatement(query);
                ResultSet rs = ps.executeQuery()) {
            while (rs.next()) {
                Long codAlumno = rs.getLong("cod_alumn");
                String nombre = rs.getString("nombre");
                String apellido = rs.getString("apellido");
                int edad = rs.getInt("edad");
                int codTutor = rs.getInt("cod_tutor");

                Alumno a = new Alumno(codAlumno, nombre, apellido, edad, codTutor);
                alumnos.add(a);
            }
        }

        return alumnos;
    }

    @Override
    public Alumno obtenerAlumno(Long id) throws SQLException{
        final String query = "SELECT cod_alumn, nombre, apellido, edad, cod_tutor FROM alumno WHERE cod_alumn = ?";
        try (PreparedStatement ps = conn.prepareStatement(query)) {
            ps.setLong(1, id);
            ResultSet rs = ps.executeQuery();
                if (rs.next()){
                    Long cod = rs.getLong("cod_alumn");
                    String nombre = rs.getString("nombre");
                    String apellido = rs.getString("apellido");
                    int edad = rs.getInt("edad");
                    int codTutor = rs.getInt("cod_tutor");
                return new Alumno(cod, nombre, apellido, edad, codTutor);
                }
        }
        return null;
    }

    @Override
    public List<String> listarRelacionados() throws SQLException {
    final String query = """
        SELECT a.nombre  AS nombre_alumno,
                a.apellido AS apellido_alumno,
                p.nombre  AS nombre_profesor
        FROM   alumno a , profesor p
        WHERE a.cod_tutor = p.cod_prof
        ORDER BY a.nombre
        """;

    List<String> resultado = new ArrayList<>();

    try (PreparedStatement ps = conn.prepareStatement(query);
        ResultSet rs = ps.executeQuery()) {

        while (rs.next()) {
            String nombreAlumno   = rs.getString("nombre_alumno");
            String apellidoAlumno = rs.getString("apellido_alumno");
            String nombreProfesor = rs.getString("nombre_profesor");
            resultado.add(String.format("Alumno : %s %s - Tutor : %s", nombreAlumno, apellidoAlumno, nombreProfesor));
        }
    }

    return resultado;
}

}
